apiVersion: v1
kind: Service
metadata:
    labels:
        app: adminer
    name: adminer
spec:
    ports:
        - name: "8080"
          port: {{ .Values.adminerPort }}
          targetPort: {{ .Values.adminerPort }}
    selector:
        app: adminer
