apiVersion: v1
kind: Service
metadata:
    labels:
        app: db
    name: db
spec:
    ports:
        - name: "3306"
          port: {{ .Values.dbPort }}
          targetPort: {{ .Values.dbPort }}
    selector:
        app: db
