apiVersion: v1
kind: Service
metadata:
    labels:
        app: frontend
    name: frontend
spec:
    ports:
        - name: "3002"
          port: {{ .Values.frontendPort }}
          targetPort: {{ .Values.frontendPort }}
    selector:
        app: frontend
