apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: reader
rules:
    - apiGroups: [""]
      resources: ["pod", "service", "ingress"]
      verbs: ["get", "watch", "list"]
